"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import os
import shutil
from setuptools import setup

# Base Name (used for .app & .dmg, prompted in the finder bar)
APP_BASE_NAME = 'Ninja IDE'

APP_NAME = APP_BASE_NAME + '.app'
SCRIPT_NAME = APP_BASE_NAME + '.py'
DMG_NAME = APP_BASE_NAME + '.dmg'
shutil.copy('ninja-ide.py', SCRIPT_NAME)
APP = [SCRIPT_NAME]
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
     'includes': [
         'PyQt4',
         'sip',
         'watchdog',
         'ninja_ide.addins'
     ],
     'iconfile': 'icon.icns'
}

# Build app
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

# Copy addins to resources
for resource in ('addins', 'doc', 'img'):
    shutil.copytree(
        os.path.join(os.path.dirname(__file__), 'ninja_ide', resource),
        os.path.join(os.path.dirname(__file__), 'dist',
        APP_NAME, 'Contents', 'Resources', resource),
    )

# Deploy QT in app
os.system('cd "%s";macdeployqt "%s"' % (
    os.path.join(os.path.dirname(__file__), 'dist'),
    APP_NAME
))

# Generate the dmg image
os.system('hdiutil create "%s" -srcfolder "%s" -ov' % (
    os.path.join(os.path.dirname(__file__), 'dist', DMG_NAME),
    os.path.join(os.path.dirname(__file__), 'dist')
))
